### ISSUE TITLE
Добавлен хук для проверки коммитов

### ISSUE THREAD

**Issue by crckhd** [crckhd/Meetogram#6]
Нужно добавить hook в CI/CD, который бы проверял коммиты на их правильное написание:

```yaml
name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
```

По умолчанию мы будем использовать [Conventional Commits](https://www.conventionalcommits.org/ru/v1.0.0/)
